# -*- coding: utf-8 -*-
"""analisis_aqualimpia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUIyx2gLtvbZahnI2nCwUUUmfkfJAx4k

# Análisis de desempeño de plantas – AquaLimpia S. A.
Evaluación de tres hipótesis sobre los incumplimientos de DBO del efluente: caudal de entrada (H1), carga contaminante (H2) y diferencias entre plantas (H3), junto con una evaluación de la calidad de los datos.

## 1. Preparación del entorno
Clona el repositorio solo si no existe (celda idempotente), registra las versiones de las librerías e importa las funciones de `src/`.
"""

import os
import subprocess
import sys

REPO = '/content/aqualimpia-analisis'

# En Colab: clona el repositorio si no existe y entra a él.
# Fuera de Colab: se asume que el script se ejecuta desde la raíz del repositorio.
if os.path.exists('/content'):
    if not os.path.exists(REPO):
        subprocess.run(['git', 'clone', 'https://github.com/SimplyNameless/aqualimpia-analisis.git', REPO],
                       check=True)
    os.chdir(REPO)

sys.path.insert(0, os.getcwd())

print('Directorio de trabajo:', os.getcwd())
print('data:', os.listdir('data'))
print('src:', os.listdir('src'))

import sys, pandas, numpy, matplotlib, seaborn, scipy, openpyxl, joblib

print(f'# Python {sys.version.split()[0]}')
for lib in [pandas, numpy, matplotlib, seaborn, scipy, openpyxl, joblib]:
    print(f'{lib.__name__}=={lib.__version__}')

from src.procesamiento import cargar_datos, calcular_eficiencia, marcar_alertas
from src.analisis import correlaciones, resumen_por_planta, prueba_chi2
from src.reportes import exportar_reportes, guardar_resultados, cargar_resultados
from src.calidad import (resumen_completitud, revisar_duplicados, revisar_rangos,
                         detectar_atipicos_iqr, revisar_consistencia_cumplimiento,
                         cobertura_temporal)

print('Módulos cargados correctamente')

"""## 2. Carga de datos
`cargar_datos` lee el dataset y convierte la fecha con formato explícito, para evitar confusiones entre día y mes.
"""

import pandas as pd

df = cargar_datos('data/dataset_set_A_aguas_residuales.xlsx')

print(df.shape)
print('Desde:', df['fecha_registro'].min())
print('Hasta:', df['fecha_registro'].max())
df.info()
df.head()

"""## 3. Variable derivada: eficiencia de remoción
Porcentaje de DBO eliminado por la planta. Permite comparar plantas que reciben cargas distintas.
"""

df = calcular_eficiencia(df)

df['eficiencia_remocion_pct'].describe()

"""## 4. Calidad de los datos
### 4.1 Completitud y unicidad
Se distinguen los duplicados exactos (filas idénticas) de los registros que repiten planta y fecha con valores distintos.
"""

print(resumen_completitud(df), '\n')

dup = revisar_duplicados(df, ['fecha_registro', 'planta'])
print('Duplicados exactos:', dup['duplicados_exactos'])
print('Registros con planta y fecha repetidas:', dup['registros_con_clave_repetida'])
print('Combinaciones planta-fecha repetidas:', dup['combinaciones_repetidas'], '\n')

dup['detalle'].head(6)

"""### 4.2 Análisis de sensibilidad
Se repiten las pruebas principales excluyendo todos los registros repetidos, para verificar si las conclusiones dependen de ellos.
"""

sin_repetidos = df[~df.duplicated(['fecha_registro', 'planta'], keep=False)]
print('Registros sin planta-fecha repetida:', len(sin_repetidos), '\n')

print(correlaciones(sin_repetidos, 'DBO_salida_mg_L',
                    ['DBO_entrada_mg_L', 'caudal_entrada_m3_d']), '\n')

chi_sin_rep = prueba_chi2(sin_repetidos, 'planta', 'cumplimiento_norma')
print(f"Chi-cuadrado plantas, p-valor: {chi_sin_rep['p_valor']:.3f}")

"""### 4.3 Validez y valores atípicos
Fuera de rango = físicamente imposible. Atípico = estadísticamente inusual, pero posiblemente real. Los atípicos se reportan, no se eliminan.
"""

reglas = {
    'caudal_entrada_m3_d': (0, float('inf')),
    'DBO_entrada_mg_L': (0, float('inf')),
    'SST_entrada_mg_L': (0, float('inf')),
    'pH_entrada': (0, 14),
    'energia_aeracion_kWh': (0, float('inf')),
    'lodos_generados_kg_d': (0, float('inf')),
    'DBO_salida_mg_L': (0, float('inf')),
    'eficiencia_remocion_pct': (0, 100),
}

print(revisar_rangos(df, reglas).to_string(index=False), '\n')
print(detectar_atipicos_iqr(df, list(reglas)).to_string(index=False))

"""### 4.4 Consistencia de la etiqueta y cobertura temporal
Si el cumplimiento dependiera solo de la DBO, ningún registro "No cumple" debería tener DBO menor o igual al máximo de los que cumplen.
"""

cons = revisar_consistencia_cumplimiento(df)

print(f"DBO de salida máxima entre registros que CUMPLEN:    {cons['max_valor_cumple']} mg/L")
print(f"DBO de salida mínima entre registros que NO CUMPLEN: {cons['min_valor_no_cumple']} mg/L")
print(f"Registros 'No cumple' con DBO ≤ {cons['max_valor_cumple']} mg/L: "
      f"{cons['no_cumple_bajo_umbral']} de {cons['total_no_cumple']}\n")

print(cobertura_temporal(df))

"""### 4.5 ¿Qué distingue a los incumplimientos con DBO baja?
Comparación de variables entre registros que cumplen y no cumplen con DBO de salida ≤ 29,5 mg/L, y prueba t de Welch.
"""

bajo_umbral = df[df['DBO_salida_mg_L'] <= cons['max_valor_cumple']]

(bajo_umbral
 .groupby('cumplimiento_norma')[['SST_entrada_mg_L', 'pH_entrada', 'DBO_entrada_mg_L', 'caudal_entrada_m3_d']]
 .mean()
 .round(2))

from scipy import stats

no_cumple = bajo_umbral[bajo_umbral['cumplimiento_norma'] == 0]
cumple = bajo_umbral[bajo_umbral['cumplimiento_norma'] == 1]

for var in ['SST_entrada_mg_L', 'caudal_entrada_m3_d']:
    t, p = stats.ttest_ind(no_cumple[var], cumple[var], equal_var=False)
    print(f'{var}: t = {t:.2f}, p-valor = {p:.4g}')

"""## 5. Análisis de hipótesis
### H1 y H2: correlación con la DBO de salida
La eficiencia se excluye porque se calcula a partir de la DBO de salida (relación circular).
"""

variables = ['caudal_entrada_m3_d', 'DBO_entrada_mg_L', 'SST_entrada_mg_L',
             'pH_entrada', 'energia_aeracion_kWh', 'lodos_generados_kg_d']

tabla_corr = correlaciones(df, 'DBO_salida_mg_L', variables)
tabla_corr

"""### H3: diferencias entre plantas
Promedios por planta, intervalos de confianza del 95 % de la eficiencia y prueba chi-cuadrado de independencia.
"""

resumen_plantas = resumen_por_planta(df)
resumen_plantas

chi = prueba_chi2(df, 'planta', 'cumplimiento_norma')
p_valor = chi['p_valor']

print(chi['tabla'], '\n')
print(f"Chi-cuadrado: {chi['chi2']:.3f}")
print(f"Grados de libertad: {chi['gl']}")
print(f'p-valor: {p_valor:.3f}')

"""## 6. Dashboard exploratorio
Un panel por hipótesis. Los valores de r, p y fechas se calculan en el código.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import os

os.makedirs('dashboard', exist_ok=True)

orden_plantas = sorted(df['planta'].unique())
estado = df['cumplimiento_norma'].map({0: 'No cumple', 1: 'Cumple'})
colores = {'No cumple': '#d62728', 'Cumple': '#2ca02c'}

r_carga = df['DBO_entrada_mg_L'].corr(df['DBO_salida_mg_L'])
r_caudal = df['caudal_entrada_m3_d'].corr(df['DBO_salida_mg_L'])

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Dashboard exploratorio – Desempeño de plantas AquaLimpia S.A.\n'
             f'({df["fecha_registro"].min():%d-%m-%Y} a {df["fecha_registro"].max():%d-%m-%Y}, n = {len(df)})',
             fontsize=14, fontweight='bold')

# Panel 1 – H2: carga contaminante
sns.scatterplot(x=df['DBO_entrada_mg_L'], y=df['DBO_salida_mg_L'], hue=estado,
                palette=colores, alpha=0.7, ax=axes[0, 0])
axes[0, 0].set_title(f'H2: DBO entrada vs DBO salida (r = {r_carga:.2f})')
axes[0, 0].set_xlabel('DBO entrada (mg/L)')
axes[0, 0].set_ylabel('DBO salida (mg/L)')
axes[0, 0].legend(title='Estado')

# Panel 2 – H1: caudal
sns.scatterplot(x=df['caudal_entrada_m3_d'], y=df['DBO_salida_mg_L'], hue=estado,
                palette=colores, alpha=0.7, ax=axes[0, 1])
axes[0, 1].set_title(f'H1: Caudal de entrada vs DBO salida (r = {r_caudal:.2f})')
axes[0, 1].set_xlabel('Caudal de entrada (m³/d)')
axes[0, 1].set_ylabel('DBO salida (mg/L)')
axes[0, 1].legend(title='Estado')

# Panel 3 – H3: eficiencia por planta
sns.boxplot(data=df, x='planta', y='eficiencia_remocion_pct', order=orden_plantas, ax=axes[1, 0])
axes[1, 0].set_title('H3: Eficiencia de remoción de DBO por planta')
axes[1, 0].set_xlabel('')
axes[1, 0].set_ylabel('Eficiencia (%)')

# Panel 4 – H3: cumplimiento por planta
barras = axes[1, 1].bar(orden_plantas, resumen_plantas.loc[orden_plantas, 'tasa_cumplimiento_pct'],
                        color='#1f77b4')
axes[1, 1].bar_label(barras, fmt='%.1f%%')
axes[1, 1].set_title(f'H3: Tasa de cumplimiento normativo (χ² p = {p_valor:.2f})')
axes[1, 1].set_ylabel('Cumplimiento (%)')
axes[1, 1].set_ylim(0, 100)

plt.tight_layout()
plt.savefig('dashboard/dashboard_exploratorio.png', dpi=150, bbox_inches='tight')
plt.show()

"""## 7. Reportes por área y validación de alertas
Umbrales de alerta exploratorios (percentiles 75 y 10), no normativos. La validación reutiliza `prueba_chi2` con otras variables.
"""

df, umbrales = marcar_alertas(df)
ruta_op, ruta_amb = exportar_reportes(df)

print(f"Umbral carga alta (P75): {umbrales['carga_alta_mg_L']:.1f} mg/L")
print(f"Umbral eficiencia baja (P10): {umbrales['eficiencia_baja_pct']:.2f} %")
print(df[['alerta_carga_alta', 'alerta_eficiencia_baja']].sum(), '\n')
print('Reportes generados:')
print(ruta_op)
print(ruta_amb)

validacion = prueba_chi2(df, 'alerta_carga_alta', 'cumplimiento_norma')

print(validacion['tabla'], '\n')
print(f"Chi-cuadrado: {validacion['chi2']:.3f}")
print(f"p-valor: {validacion['p_valor']:.4f}")

"""## 8. Resultados serializados
Se guardan con Joblib para reutilizarlos sin volver a ejecutar el análisis.
"""

resultados = {
    'correlaciones': tabla_corr,
    'resumen_plantas': resumen_plantas,
    'chi2_plantas': chi,
    'chi2_alerta': validacion,
    'umbrales': umbrales,
}

ruta = guardar_resultados(resultados)
print('Resultados guardados en:', ruta, '\n')

# Verificación: recuperar lo guardado
recuperados = cargar_resultados(ruta)
print('Contenido:', list(recuperados.keys()), '\n')
print(recuperados['correlaciones'])
